.TH TAGTOOL 1 "October 2004" "Audio Tag Tool" "User Commands"
.SH NAME
tagtool \- a tool to tag and rename MP3 and Ogg Vorbis files.
.SH SYNOPSIS
.B tagtool
[\fIDIR\fR]...
.SH DESCRIPTION
.B tagtool
is a program to manage the information fields in MP3 and Ogg Vorbis files
(commonly called tags). Tag Tool can be used to edit tags one by one, but the
most useful features are mass tag and mass rename. These are designed to tag or
rename hundreds of files at once, in any desired format.
.PP
Supplying an optional directory argument on the command line will cause tagtool
to start in that directory.
.PP
The following options are supported:
.TP
\fB\-\-dump\fR \fIFILE\fR
Dump all known information about FILE and exit.
.TP
\fB\-\-help\fR
Print a short help message and exit.
.TP
\fB\-\-version\fR
Print the program version and exit.
.SH SEE ALSO
.BR Homepage:
<http://sourceforge.net/projects/tagtool/>
.SH AUTHOR
tagtool was written by Pedro Lopes <paol1976@yahoo.com>
.SH COPYRIGHT
Copyright \(co 2004-2007 Pedro Lopes <paol1976@yahoo.com>
.PP
This manual page was written by Pedro Lopes and formatted by Kartik Mistry
<kartik@debian.org>, for the Debian project (but may be used by others).
